name: workshop1-env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.1
  - python=3.11.4
  - pip=23.3.1
  - ipykernel=7.0.1
  - numpy=1.24.3
  - xarray=2024.10.0
  - netcdf4=1.7.4